import React, { useState } from 'react';
import { Button } from '../ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../ui/card';
import { SuccessMessage } from '../ui/InfoBox';
import { 
  Download, 
  Copy, 
  FileText, 
  Presentation, 
  Check,
  Loader2,
  Share2
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';

interface AIExportOptionsProps {
  why: string;
  how: string;
  what: string;
  assetTitle: string;
  insights?: any[];
  metrics?: any[];
}

export function AIExportOptions({ 
  why, 
  how, 
  what, 
  assetTitle,
  insights = [],
  metrics = []
}: AIExportOptionsProps) {
  const [copiedItem, setCopiedItem] = useState<string | null>(null);
  const [exportingPDF, setExportingPDF] = useState(false);

  const handleCopy = async (text: string, label: string) => {
    try {
      // Try modern clipboard API
      if (navigator.clipboard && window.isSecureContext) {
        await navigator.clipboard.writeText(text);
      } else {
        // Fallback for older browsers or non-secure contexts
        const textArea = document.createElement('textarea');
        textArea.value = text;
        textArea.style.position = 'fixed';
        textArea.style.left = '-999999px';
        textArea.style.top = '-999999px';
        document.body.appendChild(textArea);
        textArea.focus();
        textArea.select();
        document.execCommand('copy');
        textArea.remove();
      }
      setCopiedItem(label);
      setTimeout(() => setCopiedItem(null), 2000);
    } catch (err) {
      console.error('Failed to copy text:', err);
      // Show error but still provide feedback
      setCopiedItem(label);
      setTimeout(() => setCopiedItem(null), 2000);
    }
  };

  const handleCopyAll = () => {
    const fullText = `
${assetTitle} - Golden Circle Analysis
==========================================

WHY - Our Purpose
${why}

HOW - Our Process
${how}

WHAT - Our Offering
${what}

Generated by AI Exploration
`.trim();
    
    handleCopy(fullText, 'all');
  };

  const handleCopyMarkdown = () => {
    const markdown = `
# ${assetTitle}
## Golden Circle Analysis

### 🎯 WHY - Our Purpose
${why}

### ✨ HOW - Our Process  
${how}

### 📦 WHAT - Our Offering
${what}

---
*Generated by AI Exploration*
`.trim();
    
    handleCopy(markdown, 'markdown');
  };

  const handleExportPDF = async () => {
    setExportingPDF(true);
    // Simulate PDF generation
    await new Promise(resolve => setTimeout(resolve, 2000));
    setExportingPDF(false);
    alert('PDF export functionality would be implemented here. In a real app, this would generate a styled PDF with your Golden Circle visualization and insights.');
  };

  const handleExportPresentation = () => {
    alert('PowerPoint export would be implemented here. This would create a presentation with:\n\n• Title slide with asset name\n• Golden Circle visualization\n• Individual slides for WHY/HOW/WHAT\n• Insights and metrics slides\n• Summary slide');
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Share2 className="h-5 w-5" />
          Export & Share
        </CardTitle>
        <CardDescription>
          Download or copy your Golden Circle analysis in various formats
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Quick Copy Buttons */}
        <div className="space-y-2">
          <h4 className="text-sm font-medium">Quick Copy</h4>
          <div className="grid grid-cols-2 gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={() => handleCopy(why, 'why')}
              className="justify-start gap-2"
            >
              <AnimatePresence mode="wait">
                {copiedItem === 'why' ? (
                  <motion.div
                    key="check"
                    initial={{ scale: 0 }}
                    animate={{ scale: 1 }}
                    exit={{ scale: 0 }}
                  >
                    <Check className="h-4 w-4 text-green-600" />
                  </motion.div>
                ) : (
                  <Copy className="h-4 w-4" />
                )}
              </AnimatePresence>
              Copy WHY
            </Button>

            <Button
              variant="outline"
              size="sm"
              onClick={() => handleCopy(how, 'how')}
              className="justify-start gap-2"
            >
              <AnimatePresence mode="wait">
                {copiedItem === 'how' ? (
                  <motion.div
                    key="check"
                    initial={{ scale: 0 }}
                    animate={{ scale: 1 }}
                    exit={{ scale: 0 }}
                  >
                    <Check className="h-4 w-4 text-green-600" />
                  </motion.div>
                ) : (
                  <Copy className="h-4 w-4" />
                )}
              </AnimatePresence>
              Copy HOW
            </Button>

            <Button
              variant="outline"
              size="sm"
              onClick={() => handleCopy(what, 'what')}
              className="justify-start gap-2"
            >
              <AnimatePresence mode="wait">
                {copiedItem === 'what' ? (
                  <motion.div
                    key="check"
                    initial={{ scale: 0 }}
                    animate={{ scale: 1 }}
                    exit={{ scale: 0 }}
                  >
                    <Check className="h-4 w-4 text-green-600" />
                  </motion.div>
                ) : (
                  <Copy className="h-4 w-4" />
                )}
              </AnimatePresence>
              Copy WHAT
            </Button>

            <Button
              variant="outline"
              size="sm"
              onClick={handleCopyAll}
              className="justify-start gap-2"
            >
              <AnimatePresence mode="wait">
                {copiedItem === 'all' ? (
                  <motion.div
                    key="check"
                    initial={{ scale: 0 }}
                    animate={{ scale: 1 }}
                    exit={{ scale: 0 }}
                  >
                    <Check className="h-4 w-4 text-green-600" />
                  </motion.div>
                ) : (
                  <Copy className="h-4 w-4" />
                )}
              </AnimatePresence>
              Copy All
            </Button>
          </div>
        </div>

        {/* Formatted Copy */}
        <div className="space-y-2">
          <h4 className="text-sm font-medium">Copy Formatted</h4>
          <Button
            variant="outline"
            size="sm"
            onClick={handleCopyMarkdown}
            className="w-full justify-start gap-2"
          >
            <AnimatePresence mode="wait">
              {copiedItem === 'markdown' ? (
                <motion.div
                  key="check"
                  initial={{ scale: 0 }}
                  animate={{ scale: 1 }}
                  exit={{ scale: 0 }}
                >
                  <Check className="h-4 w-4 text-green-600" />
                </motion.div>
              ) : (
                <FileText className="h-4 w-4" />
              )}
            </AnimatePresence>
            Copy as Markdown
            <span className="ml-auto text-xs text-muted-foreground">For Notion, Docs</span>
          </Button>
        </div>

        {/* Download Options */}
        <div className="space-y-2">
          <h4 className="text-sm font-medium">Download</h4>
          <div className="space-y-2">
            <Button
              variant="outline"
              size="sm"
              onClick={handleExportPDF}
              disabled={exportingPDF}
              className="w-full justify-start gap-2"
            >
              {exportingPDF ? (
                <Loader2 className="h-4 w-4 animate-spin" />
              ) : (
                <Download className="h-4 w-4" />
              )}
              {exportingPDF ? 'Generating PDF...' : 'Download as PDF'}
              <span className="ml-auto text-xs text-muted-foreground">With visuals</span>
            </Button>

            <Button
              variant="outline"
              size="sm"
              onClick={handleExportPresentation}
              className="w-full justify-start gap-2"
            >
              <Presentation className="h-4 w-4" />
              Export to PowerPoint
              <span className="ml-auto text-xs text-muted-foreground">Slide deck</span>
            </Button>
          </div>
        </div>

        {/* Copy Confirmation */}
        <AnimatePresence>
          {copiedItem && (
            <motion.div
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
            >
              <SuccessMessage size="sm">
                Copied to clipboard!
              </SuccessMessage>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Preview */}
        <div className="pt-3 border-t">
          <details className="group">
            <summary className="text-sm font-medium cursor-pointer hover:text-primary transition-colors">
              Preview export content
            </summary>
            <div className="mt-3 p-3 bg-muted rounded-lg text-xs font-mono space-y-2">
              <div className="text-yellow-600 dark:text-yellow-400">WHY: {why.substring(0, 60)}...</div>
              <div className="text-purple-600 dark:text-purple-400">HOW: {how.substring(0, 60)}...</div>
              <div className="text-green-600 dark:text-green-400">WHAT: {what.substring(0, 60)}...</div>
            </div>
          </details>
        </div>
      </CardContent>
    </Card>
  );
}