/**
 * Relationship System Types
 * Defines how different entities (Brand Assets, Personas, Research Plans, etc.) relate to each other
 */

export type EntityType = 
  | 'brand-asset' 
  | 'persona' 
  | 'research-plan' 
  | 'trend' 
  | 'strategy-tool' 
  | 'knowledge'
  | 'product';

export type RelationType = 
  | 'informs'        // Brand Asset informs Persona (e.g., Golden Circle → Persona goals)
  | 'validates'      // Research Plan validates Brand Asset
  | 'influences'     // Trend influences Brand Asset
  | 'uses'           // Strategy Tool uses Brand Asset
  | 'targets'        // Research Plan targets Persona
  | 'references'     // Knowledge item references Brand Asset
  | 'derives-from'   // Asset derives from another (e.g., Mission from Vision)
  | 'conflicts-with' // Potential inconsistency detected
  | 'supports';      // Asset supports another

export type RelationshipStrength = 'weak' | 'medium' | 'strong';

export type RelationshipStatus = 'active' | 'proposed' | 'archived' | 'conflict';

export interface Relationship {
  id: string;
  sourceType: EntityType;
  sourceId: string;
  sourceName: string;
  targetType: EntityType;
  targetId: string;
  targetName: string;
  relationType: RelationType;
  strength: RelationshipStrength;
  status: RelationshipStatus;
  createdAt: string;
  createdBy?: string;
  updatedAt?: string;
  metadata?: {
    autoGenerated?: boolean;
    confidence?: number; // 0-1 score for AI-suggested relationships
    notes?: string;
    keywords?: string[]; // Matching keywords that created this relationship
    validatedBy?: string; // User who validated an AI-suggested relationship
    validatedAt?: string;
  };
}

export interface ImpactAnalysis {
  entityType: EntityType;
  entityId: string;
  entityName: string;
  riskLevel: 'low' | 'medium' | 'high' | 'critical';
  directImpacts: number;
  indirectImpacts: number;
  totalAffected: number;
  affectedByType: {
    personas: EntityReference[];
    brandAssets: EntityReference[];
    researchPlans: EntityReference[];
    strategyTools: EntityReference[];
    trends: EntityReference[];
    knowledge: EntityReference[];
    products: EntityReference[];
  };
  criticalRelationships: Relationship[];
  recommendations: string[];
  estimatedUpdateTime?: string; // e.g., "2-3 hours"
}

export interface EntityReference {
  id: string;
  type: EntityType;
  name: string;
  relationshipType: RelationType;
  strength: RelationshipStrength;
  lastUpdated?: string;
}

export interface ConsistencyIssue {
  id: string;
  severity: 'critical' | 'warning' | 'info';
  type: 'semantic-conflict' | 'missing-connection' | 'stale-reference' | 'keyword-gap' | 'value-mismatch';
  title: string;
  description: string;
  affectedEntities: EntityReference[];
  detectedAt: string;
  suggestedAction: string;
  autoFixable: boolean;
  autoFixAction?: () => void;
  priority: number; // 1-10, higher = more urgent
}

export interface ConsistencyReport {
  generatedAt: string;
  totalIssues: number;
  criticalCount: number;
  warningCount: number;
  infoCount: number;
  overallScore: number; // 0-100, health score
  issues: ConsistencyIssue[];
  summary: {
    strongestAsset?: EntityReference; // Most connected
    weakestAsset?: EntityReference; // Least connected
    mostConflicts?: EntityReference;
    recentlyUpdated: EntityReference[];
    needsAttention: EntityReference[];
  };
}

export interface Suggestion {
  id: string;
  type: 'next-asset' | 'relationship' | 'research' | 'warning' | 'maintenance' | 'opportunity';
  priority: 'critical' | 'high' | 'medium' | 'low';
  urgent?: boolean;
  title: string;
  description: string;
  reasoning?: string;
  action: string;
  actionUrl: string;
  icon: string;
  estimatedTime?: string;
  estimatedImpact?: 'high' | 'medium' | 'low';
  stats?: {
    label: string;
    value: number;
  };
  relatedEntities?: EntityReference[];
  dismissible?: boolean;
  expiresAt?: string; // Time-sensitive suggestions
}

export interface RelationshipGraph {
  nodes: GraphNode[];
  edges: GraphEdge[];
  clusters: GraphCluster[];
}

export interface GraphNode {
  id: string;
  type: EntityType;
  name: string;
  status?: string;
  connections: number;
  centrality: number; // How central/important this node is (0-1)
  lastUpdated?: string;
}

export interface GraphEdge {
  id: string;
  source: string;
  target: string;
  relationType: RelationType;
  strength: RelationshipStrength;
  bidirectional?: boolean;
}

export interface GraphCluster {
  id: string;
  name: string;
  nodes: string[];
  description?: string;
  health: 'healthy' | 'needs-attention' | 'critical';
}

export interface RelationshipStats {
  totalRelationships: number;
  byType: Record<RelationType, number>;
  byStrength: Record<RelationshipStrength, number>;
  averageConnectionsPerAsset: number;
  mostConnectedEntity: EntityReference;
  leastConnectedEntity: EntityReference;
  orphanedEntities: EntityReference[]; // Entities with no relationships
  recentlyCreated: Relationship[];
  aiSuggestedCount: number;
  userCreatedCount: number;
}
