import { Relationship } from '../types/relationship';

/**
 * Mock Relationships Data
 * Demonstrates how different entities relate to each other in the system
 */

export const mockRelationships: Relationship[] = [
  // Golden Circle → Personas
  {
    id: 'rel-1',
    sourceType: 'brand-asset',
    sourceId: '1',
    sourceName: 'Golden Circle Framework',
    targetType: 'persona',
    targetId: 'p1',
    targetName: 'Tech-Savvy Millennial',
    relationType: 'informs',
    strength: 'strong',
    status: 'active',
    createdAt: '2025-01-15T10:00:00Z',
    metadata: {
      autoGenerated: true,
      confidence: 0.92,
      keywords: ['innovation', 'technology', 'digital transformation'],
      notes: 'Golden Circle "Why" aligns with persona\'s goals for innovation'
    }
  },
  {
    id: 'rel-2',
    sourceType: 'brand-asset',
    sourceId: '1',
    sourceName: 'Golden Circle Framework',
    targetType: 'persona',
    targetId: 'p2',
    targetName: 'Enterprise Decision Maker',
    relationType: 'informs',
    strength: 'strong',
    status: 'active',
    createdAt: '2025-01-15T10:05:00Z',
    metadata: {
      autoGenerated: true,
      confidence: 0.88,
      keywords: ['business transformation', 'efficiency', 'ROI'],
      notes: 'Golden Circle "What" addresses enterprise needs'
    }
  },

  // Vision Statement → Mission Statement
  {
    id: 'rel-3',
    sourceType: 'brand-asset',
    sourceId: '2',
    sourceName: 'Brand Vision',
    targetType: 'brand-asset',
    targetId: '3',
    targetName: 'Mission Statement',
    relationType: 'derives-from',
    strength: 'strong',
    status: 'active',
    createdAt: '2025-01-18T14:00:00Z',
    metadata: {
      autoGenerated: false,
      notes: 'Mission is tactical execution of Vision'
    }
  },

  // Research Plans → Brand Assets
  {
    id: 'rel-4',
    sourceType: 'research-plan',
    sourceId: 'plan-1',
    sourceName: 'Q1 Brand Validation Study',
    targetType: 'brand-asset',
    targetId: '1',
    targetName: 'Golden Circle Framework',
    relationType: 'validates',
    strength: 'strong',
    status: 'active',
    createdAt: '2025-01-20T09:00:00Z',
    metadata: {
      autoGenerated: false,
      notes: 'Workshop and interviews validated Golden Circle with stakeholders'
    }
  },
  {
    id: 'rel-5',
    sourceType: 'research-plan',
    sourceId: 'plan-1',
    sourceName: 'Q1 Brand Validation Study',
    targetType: 'brand-asset',
    targetId: '2',
    targetName: 'Brand Vision',
    relationType: 'validates',
    strength: 'medium',
    status: 'active',
    createdAt: '2025-01-20T09:05:00Z',
    metadata: {
      autoGenerated: false,
      notes: 'Partial validation through customer interviews'
    }
  },

  // Brand Values → Personas
  {
    id: 'rel-6',
    sourceType: 'brand-asset',
    sourceId: '5',
    sourceName: 'Brand Values',
    targetType: 'persona',
    targetId: 'p1',
    targetName: 'Tech-Savvy Millennial',
    relationType: 'informs',
    strength: 'medium',
    status: 'active',
    createdAt: '2025-01-16T11:00:00Z',
    metadata: {
      autoGenerated: true,
      confidence: 0.75,
      keywords: ['innovation', 'authenticity', 'collaboration'],
      notes: 'Brand values resonate with persona motivations'
    }
  },

  // Archetype → Brand Personality
  {
    id: 'rel-7',
    sourceType: 'brand-asset',
    sourceId: '6',
    sourceName: 'Brand Archetype',
    targetType: 'brand-asset',
    targetId: '7',
    targetName: 'Brand Personality',
    relationType: 'informs',
    strength: 'strong',
    status: 'active',
    createdAt: '2025-01-17T15:00:00Z',
    metadata: {
      autoGenerated: false,
      notes: 'Archetype defines personality traits'
    }
  },

  // Knowledge Library → Brand Assets
  {
    id: 'rel-8',
    sourceType: 'knowledge',
    sourceId: 'doc-1',
    sourceName: 'Competitor Analysis 2024',
    targetType: 'brand-asset',
    targetId: '4',
    targetName: 'Brand Positioning',
    relationType: 'references',
    strength: 'medium',
    status: 'active',
    createdAt: '2025-01-19T10:00:00Z',
    metadata: {
      autoGenerated: true,
      confidence: 0.82,
      keywords: ['market positioning', 'differentiation', 'competitive advantage'],
      notes: 'Competitor insights inform positioning strategy'
    }
  },

  // Trend → Brand Asset (Potential Conflict)
  {
    id: 'rel-9',
    sourceType: 'trend',
    sourceId: 'trend-1',
    sourceName: 'AI-First Customer Experience',
    targetType: 'brand-asset',
    targetId: '2',
    targetName: 'Brand Vision',
    relationType: 'conflicts-with',
    strength: 'weak',
    status: 'conflict',
    createdAt: '2025-01-21T08:00:00Z',
    metadata: {
      autoGenerated: true,
      confidence: 0.65,
      notes: 'Current vision emphasizes human connection, but market is moving toward AI automation',
      keywords: ['AI', 'automation', 'efficiency']
    }
  },

  // Persona → Research Plan
  {
    id: 'rel-10',
    sourceType: 'research-plan',
    sourceId: 'plan-2',
    sourceName: 'Persona Validation Interviews',
    targetType: 'persona',
    targetId: 'p1',
    targetName: 'Tech-Savvy Millennial',
    relationType: 'targets',
    strength: 'strong',
    status: 'active',
    createdAt: '2025-01-22T13:00:00Z',
    metadata: {
      autoGenerated: false,
      notes: 'Interview series specifically targeting this persona segment'
    }
  },

  // Strategy Tool → Brand Assets
  {
    id: 'rel-11',
    sourceType: 'strategy-tool',
    sourceId: 'tool-positioning',
    sourceName: 'Brand Positioning Canvas',
    targetType: 'brand-asset',
    targetId: '1',
    targetName: 'Golden Circle Framework',
    relationType: 'uses',
    strength: 'strong',
    status: 'active',
    createdAt: '2025-01-18T16:00:00Z',
    metadata: {
      autoGenerated: false,
      notes: 'Positioning canvas uses Golden Circle as foundation'
    }
  },
  {
    id: 'rel-12',
    sourceType: 'strategy-tool',
    sourceId: 'tool-positioning',
    sourceName: 'Brand Positioning Canvas',
    targetType: 'brand-asset',
    targetId: '4',
    targetName: 'Brand Positioning',
    relationType: 'uses',
    strength: 'strong',
    status: 'active',
    createdAt: '2025-01-18T16:05:00Z',
    metadata: {
      autoGenerated: false,
      notes: 'Direct connection to positioning statement'
    }
  },

  // Cross-brand asset relationships
  {
    id: 'rel-13',
    sourceType: 'brand-asset',
    sourceId: '1',
    sourceName: 'Golden Circle Framework',
    targetType: 'brand-asset',
    targetId: '2',
    targetName: 'Brand Vision',
    relationType: 'supports',
    strength: 'strong',
    status: 'active',
    createdAt: '2025-01-15T12:00:00Z',
    metadata: {
      autoGenerated: true,
      confidence: 0.95,
      keywords: ['purpose', 'future', 'aspiration'],
      notes: 'Golden Circle "Why" directly supports Vision statement'
    }
  },
  {
    id: 'rel-14',
    sourceType: 'brand-asset',
    sourceId: '1',
    sourceName: 'Golden Circle Framework',
    targetType: 'brand-asset',
    targetId: '3',
    targetName: 'Mission Statement',
    relationType: 'supports',
    strength: 'strong',
    status: 'active',
    createdAt: '2025-01-15T12:05:00Z',
    metadata: {
      autoGenerated: true,
      confidence: 0.93,
      keywords: ['how', 'process', 'method'],
      notes: 'Golden Circle "How" aligns with Mission approach'
    }
  },

  // More persona relationships
  {
    id: 'rel-15',
    sourceType: 'brand-asset',
    sourceId: '4',
    sourceName: 'Brand Positioning',
    targetType: 'persona',
    targetId: 'p1',
    targetName: 'Tech-Savvy Millennial',
    relationType: 'informs',
    strength: 'strong',
    status: 'active',
    createdAt: '2025-01-19T14:00:00Z',
    metadata: {
      autoGenerated: true,
      confidence: 0.87,
      keywords: ['innovation', 'digital-first', 'early-adopter'],
      notes: 'Positioning specifically addresses this persona segment'
    }
  },

  // Product relationships (if applicable)
  {
    id: 'rel-16',
    sourceType: 'product',
    sourceId: 'prod-1',
    sourceName: 'Digital Transformation Suite',
    targetType: 'brand-asset',
    targetId: '1',
    targetName: 'Golden Circle Framework',
    relationType: 'supports',
    strength: 'strong',
    status: 'active',
    createdAt: '2025-01-20T11:00:00Z',
    metadata: {
      autoGenerated: false,
      notes: 'Product directly delivers on Golden Circle "What"'
    }
  },
  {
    id: 'rel-17',
    sourceType: 'product',
    sourceId: 'prod-1',
    sourceName: 'Digital Transformation Suite',
    targetType: 'persona',
    targetId: 'p2',
    targetName: 'Enterprise Decision Maker',
    relationType: 'targets',
    strength: 'strong',
    status: 'active',
    createdAt: '2025-01-20T11:05:00Z',
    metadata: {
      autoGenerated: false,
      notes: 'Product designed specifically for enterprise segment'
    }
  }
];

// Helper function to get all relationships
export function getAllRelationships(): Relationship[] {
  return mockRelationships;
}

// Helper function to get relationships for a specific entity
export function getRelationshipsForEntity(entityType: string, entityId: string): Relationship[] {
  return mockRelationships.filter(rel => 
    (rel.sourceType === entityType && rel.sourceId === entityId) ||
    (rel.targetType === entityType && rel.targetId === entityId)
  );
}

// Helper function to get relationship count by type
export function getRelationshipCountByType(): Record<string, number> {
  const counts: Record<string, number> = {};
  mockRelationships.forEach(rel => {
    counts[rel.relationType] = (counts[rel.relationType] || 0) + 1;
  });
  return counts;
}

// Helper function to get conflicts
export function getConflicts(): Relationship[] {
  return mockRelationships.filter(rel => rel.status === 'conflict');
}

// Helper function to get AI-suggested relationships
export function getAISuggestedRelationships(): Relationship[] {
  return mockRelationships.filter(rel => rel.metadata?.autoGenerated === true);
}
